// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXyMPrzOilshMxceadawdoioqEX4tXM28',
    appId: '1:965294803539:web:f4ab6c66411870c3e7d4a6',
    messagingSenderId: '965294803539',
    projectId: 'spotifyclone25',
    authDomain: 'spotifyclone25.firebaseapp.com',
    storageBucket: 'spotifyclone25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QJNyFpy-WkBetGptO7Wgq60M4WFimD0',
    appId: '1:965294803539:android:7bb7c24d856cc154e7d4a6',
    messagingSenderId: '965294803539',
    projectId: 'spotifyclone25',
    storageBucket: 'spotifyclone25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4bNHu_mt9A_9l8fR1sVS1CaSCbHsZH4',
    appId: '1:965294803539:ios:1d563162ba7cfaf9e7d4a6',
    messagingSenderId: '965294803539',
    projectId: 'spotifyclone25',
    storageBucket: 'spotifyclone25.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4bNHu_mt9A_9l8fR1sVS1CaSCbHsZH4',
    appId: '1:965294803539:ios:1d563162ba7cfaf9e7d4a6',
    messagingSenderId: '965294803539',
    projectId: 'spotifyclone25',
    storageBucket: 'spotifyclone25.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXyMPrzOilshMxceadawdoioqEX4tXM28',
    appId: '1:965294803539:web:f8d4a224f38f5466e7d4a6',
    messagingSenderId: '965294803539',
    projectId: 'spotifyclone25',
    authDomain: 'spotifyclone25.firebaseapp.com',
    storageBucket: 'spotifyclone25.firebasestorage.app',
  );
}
